name: build-n64-rom
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dragonminded/libdragon:latest
    steps:
      - uses: actions/checkout@v4

      - name: Show env (diagnose)
        run: |
          set -x
          echo "N64_INST=$N64_INST"
          ls -la
          ls -la src || true

      - name: Build ROM (verbose)
        run: |
          export N64_INST=/opt/libdragon
          make clean || true
          make -j1 V=1

      - name: Upload ROM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mpk_dump_fla
          path: |
            *.z64
            *.v64
            *.n64
